### ISSUE TITLE
Add dependencies which commerce bundle needs

### ISSUE THREAD

**Issue by sunnygao** [lr-whitehat/liferay-commerce-dependencies#1]

**Comment by samuelkong** [comment]
@sunnygao 
Is this needed? https://github.com/lr-whitehat/liferay-commerce-dependencies/blob/7.1.x/.gradle/caches/modules-2/files-2.1/com.liferay.commerce/com.liferay.commerce.frontend.taglib/1.0.0/7c6fcc8e106e7c13024db0455eb626d99e3160ff/com.liferay.commerce.frontend.taglib-1.0.0.jar
